root: true
env:
  es2020: true
  node: true
extends:
  - standard-with-typescript
  - prettier
  - prettier/@typescript-eslint
  - prettier/standard
plugins:
  - prettier
rules:
  # TODO: remove all
  '@typescript-eslint/explicit-function-return-type': warn
  '@typescript-eslint/strict-boolean-expressions': warn
  no-return-await: off # is fixed on eslint-config-standard@14.1.1
  prettier/prettier:
    - error
    - semi: false
      singleQuote: true
      jsxSingleQuote: true
