# vim: set ft=dockerfile:

FROM node:12-alpine as builder

WORKDIR /app/web
COPY web ./
COPY tsconfig.json ../
COPY yarn.lock .

RUN yarn install && yarn build

FROM node:12-alpine as web

ENV NODE_ENV=production
WORKDIR /app/web

COPY --from=builder /app/tsconfig.json ../
COPY --from=builder /app/web/.nuxt .nuxt
COPY --from=builder /app/web/src src
COPY --from=builder \
	/app/web/nuxt.config.ts \
	/app/web/ormconfig.ts \
	/app/web/package.json \
	/app/web/tsconfig.json \
	/app/web/yarn.lock \
	./
# COPY --from=builder /app/web/src/graphql/schema.graphql dist/graphql/

RUN yarn install

CMD ["yarn", "start"]
