version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres'
      GOOGLE_APPLICATION_CREDENTIALS: /app/web/firebase-admin.json
    extra_hosts:
      - "www.googleapis.com:172.217.25.106"
    volumes:
      - ./web:/app/web
      - ./tsconfig.json:/app/tsconfig.json
      - /app/web/node_modules
    ports:
      - "8080:3000"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: {}
