# vim: set ft=dockerfile:

FROM node:12-alpine as base

WORKDIR /app/web
COPY web/package.json .
COPY yarn.lock .

RUN yarn install
CMD ["yarn", "start:watch"]


FROM base as builder

COPY web/src ./src
COPY web/tsconfig.json .
COPY tsconfig.json ../

RUN yarn tsc --sourceMap false


FROM node:12-alpine as web

ENV NODE_ENV=production
WORKDIR /app/web

COPY --from=builder /app/web/dist dist
COPY --from=builder /app/web/src/graphql/schema.graphql dist/graphql/
COPY --from=builder /app/web/package.json /app/web/yarn.lock ./

COPY web/ormconfig.heroku.js ormconfig.js

RUN yarn install

CMD ["yarn", "start"]
