extends:
  - standard-react
  - prettier
  - prettier/react
parserOptions:
  project: ./tsconfig.json
globals:
  __DEV__: true
overrides:
  - files:
      - '**/*.tsx'
    rules:
      react/prop-types: off
